{NA <type 'exceptions.AssertionError'> AssertionError()
 Traceback (most recent call last):
  File "regression-tests/assert_test_2.py", line 6, in foo
    assert(ratio > float(tokens[1]))

Locals: {'tokens': ['1', '2'], 'line': '1 2', 'ratio': 0.5}
}
{AssertionError: Set local var 'tokens' to NA | regression-tests/assert_test_2.py foo:6}
{AssertionError: Set local var 'ratio' to NA | regression-tests/assert_test_2.py foo:6}
